/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import negocio.CadastroDeCarrosDAO;
import negocio.Carro;
import negocio.GerenciamentoDeCarrosFacade;

/**
 *
 * @author Icaro
 */
public class Janela extends javax.swing.JFrame {
    private static GerenciamentoDeCarrosFacade facade;
    private final Controller controller;
   
    /**
     * Creates new form Janela
     */
    public Janela(Controller controlador) {
        initComponents();
        facade = new GerenciamentoDeCarrosFacade();
        this.controller = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        resumo_view = new javax.swing.JPanel();
        veiculo_tab = new javax.swing.JTabbedPane();
        veiculo_pesquisa = new javax.swing.JPanel();
        painel = new javax.swing.JPanel();
        veiculoPesquisaPlaca_letra = new javax.swing.JTextField();
        veiculoPesquisaPlaca_hifen = new javax.swing.JLabel();
        veiculoPesquisaPlaca_numero = new javax.swing.JTextField();
        veiculoPesquisaPlaca_botao = new javax.swing.JButton();
        veiculoPesquisaModelo_modelo = new javax.swing.JTextField();
        veiculoPesquisaModelo_botao = new javax.swing.JButton();
        veiculoPesquisaCombustivel_combustivel = new javax.swing.JComboBox<>();
        veiculoPesquisaCombustivel_botao = new javax.swing.JButton();
        veiculoPesquisaAno_ano = new javax.swing.JTextField();
        veiculoPesquisaAno_botao = new javax.swing.JButton();
        veiculoPesquisaFabricante_fabricante = new javax.swing.JTextField();
        veiculoPesquisaFabricante_botao = new javax.swing.JButton();
        VeiculoPesquisaResultado_container = new javax.swing.JScrollPane();
        VeiculoPesquisaResultado_table = new javax.swing.JTable();
        veiculoPesquisaLista_Todos = new javax.swing.JButton();
        veiculo_cadastro = new javax.swing.JPanel();
        veiculoCadastroPlaca_letra = new javax.swing.JTextField();
        veiculoCadastroPlaca_hifen = new javax.swing.JLabel();
        veiculoCadastroPlaca_numero = new javax.swing.JTextField();
        veiculoCadastroModelo_modelo = new javax.swing.JTextField();
        veiculoCadastroAno_ano = new javax.swing.JTextField();
        veiculoCadastroCombustivel_combustivel = new javax.swing.JComboBox<>();
        veiculoCadastroFabricante_fabricante = new javax.swing.JTextField();
        labe_placa = new javax.swing.JLabel();
        labe_modelo = new javax.swing.JLabel();
        labe_fabricante = new javax.swing.JLabel();
        labe__ano = new javax.swing.JLabel();
        label_tipoDeCombustivel = new javax.swing.JLabel();
        labe_fabricante2 = new javax.swing.JLabel();
        veiculoCadastroOdometro_odometro = new javax.swing.JTextField();
        botao_cadastrarVeiculo = new javax.swing.JButton();
        veiculoCadastroTanque_capacidade = new javax.swing.JTextField();
        labe_fabricante1 = new javax.swing.JLabel();
        veiculo_relatorio = new javax.swing.JPanel();
        abastecimento_tab = new javax.swing.JTabbedPane();
        abatecimento_pesquisa = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        abastecimentoPesquisaPlaca_letra = new javax.swing.JTextField();
        abastecimentoloPesquisaPlaca_hifen = new javax.swing.JLabel();
        abastecimentoPesquisaPlaca_numero = new javax.swing.JTextField();
        abasstecimentoPesquisaPlaca_botao = new javax.swing.JButton();
        abastecimentoPesquisaModelo_modelo = new javax.swing.JTextField();
        abastecimentoPesquisaModelo_botao = new javax.swing.JButton();
        abastecimentoPesquisaCombustivel_combustivel = new javax.swing.JComboBox<>();
        abastecimentoPesquisaCombustivel_botao = new javax.swing.JButton();
        abastecimentoPesquisaAno_ano = new javax.swing.JTextField();
        abastecimentoPesquisaAno_botao = new javax.swing.JButton();
        abastecimentoPesquisaFabricante_fabricante = new javax.swing.JTextField();
        abastecimentoPesquisaFabricante_botao = new javax.swing.JButton();
        abastecimentoPesquisaResultado_container = new javax.swing.JScrollPane();
        abastecimentoPesquisaResultado_table = new javax.swing.JTable();
        veiculoPesquisaLista_Todos2 = new javax.swing.JButton();
        abatecimento_cadastro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        abastecimentoCadastroPlaca_letra = new javax.swing.JTextField();
        abastecimentoloCadastroPlaca_hifen = new javax.swing.JLabel();
        abastecimentoCadastroPlaca_numero = new javax.swing.JTextField();
        abastecimentoCadastroPlaca_botao = new javax.swing.JButton();
        abastecimentoCadastroModelo_modelo = new javax.swing.JTextField();
        abastecimentoCadastroModelo_botao = new javax.swing.JButton();
        abastecimentoCadastroCombustivel_combustivel = new javax.swing.JComboBox<>();
        abastecimentoCadastroCombustivel_botao = new javax.swing.JButton();
        abastecimentoCadastroAno_ano = new javax.swing.JTextField();
        abastecimentoCadastroAno_botao = new javax.swing.JButton();
        abastecimentoCadastroFabricante_fabricante = new javax.swing.JTextField();
        abastecimentoCadastroFabricante_botao = new javax.swing.JButton();
        abastecimentoCadastroResultado_container = new javax.swing.JScrollPane();
        abastecimentoCadastroResultado_table = new javax.swing.JTable();
        abastecimentoCadastroListaTodos = new javax.swing.JButton();
        labe_fabricante3 = new javax.swing.JLabel();
        abastecimentoCadastroOdometro_odometro = new javax.swing.JTextField();
        abastecimentoCadastroTipoDeCombustivel_combustivel = new javax.swing.JComboBox<>();
        label_tipoDeCombustivel1 = new javax.swing.JLabel();
        abastecimentoCadastroBotao_botao = new javax.swing.JButton();
        labe_fabricante4 = new javax.swing.JLabel();
        abastecimentoCadastroQuantidadeAbastecida_quantidade = new javax.swing.JTextField();
        abastecimentoCadastroValorAbastecido_valor = new javax.swing.JTextField();
        labe_fabricante5 = new javax.swing.JLabel();
        abastecimentoCadastroInicioDeSerie_checkbox = new javax.swing.JCheckBox();
        labe_fabricante6 = new javax.swing.JLabel();
        AbastecimentoCadastroData_dia = new javax.swing.JTextField();
        AbastecimentoCadastroData_mes = new javax.swing.JTextField();
        labe_fabricante7 = new javax.swing.JLabel();
        AbastecimentoCadastroData_ano = new javax.swing.JTextField();
        labe_fabricante8 = new javax.swing.JLabel();
        AbastecimentoCadastroData_hora = new javax.swing.JTextField();
        labe_fabricante9 = new javax.swing.JLabel();
        AbastecimentoCadastroData_min = new javax.swing.JTextField();
        labe_fabricante10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout resumo_viewLayout = new javax.swing.GroupLayout(resumo_view);
        resumo_view.setLayout(resumo_viewLayout);
        resumo_viewLayout.setHorizontalGroup(
            resumo_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        resumo_viewLayout.setVerticalGroup(
            resumo_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Resumo", resumo_view);

        veiculoPesquisaPlaca_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaPlaca_letraActionPerformed(evt);
            }
        });

        veiculoPesquisaPlaca_hifen.setText("-");

        veiculoPesquisaPlaca_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaPlaca_numeroActionPerformed(evt);
            }
        });

        veiculoPesquisaPlaca_botao.setText("Placa");
        veiculoPesquisaPlaca_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaPlaca_botaoActionPerformed(evt);
            }
        });

        veiculoPesquisaModelo_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaModelo_modeloActionPerformed(evt);
            }
        });

        veiculoPesquisaModelo_botao.setText("Modelo");
        veiculoPesquisaModelo_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaModelo_botaoActionPerformed(evt);
            }
        });

        veiculoPesquisaCombustivel_combustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Álcool", "Flex", "Diesel" }));

        veiculoPesquisaCombustivel_botao.setText("Combustivel");
        veiculoPesquisaCombustivel_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaCombustivel_botaoActionPerformed(evt);
            }
        });

        veiculoPesquisaAno_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaAno_anoActionPerformed(evt);
            }
        });

        veiculoPesquisaAno_botao.setText("Ano");
        veiculoPesquisaAno_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaAno_botaoActionPerformed(evt);
            }
        });

        veiculoPesquisaFabricante_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaFabricante_fabricanteActionPerformed(evt);
            }
        });

        veiculoPesquisaFabricante_botao.setText("Fabricante");
        veiculoPesquisaFabricante_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaFabricante_botaoActionPerformed(evt);
            }
        });

        VeiculoPesquisaResultado_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String [] {
                "Placa", "Fabricante", "Modelo", "Ano", "Combustível", "Odômetro"
            }
        ));
        VeiculoPesquisaResultado_container.setViewportView(VeiculoPesquisaResultado_table);

        veiculoPesquisaLista_Todos.setText("Listar Todos");
        veiculoPesquisaLista_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaLista_TodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VeiculoPesquisaResultado_container, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(veiculoPesquisaAno_ano)
                        .addGap(7, 7, 7)
                        .addComponent(veiculoPesquisaAno_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addComponent(veiculoPesquisaPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veiculoPesquisaPlaca_hifen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veiculoPesquisaPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(veiculoPesquisaPlaca_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veiculoPesquisaModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(veiculoPesquisaFabricante_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(veiculoPesquisaModelo_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(veiculoPesquisaCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(veiculoPesquisaCombustivel_botao))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(veiculoPesquisaLista_Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoPesquisaPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaPlaca_botao)
                    .addComponent(veiculoPesquisaPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaPlaca_hifen)
                    .addComponent(veiculoPesquisaModelo_botao)
                    .addComponent(veiculoPesquisaCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaCombustivel_botao)
                    .addComponent(veiculoPesquisaModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoPesquisaAno_botao)
                    .addComponent(veiculoPesquisaAno_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaFabricante_botao)
                    .addComponent(veiculoPesquisaFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaLista_Todos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VeiculoPesquisaResultado_container, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout veiculo_pesquisaLayout = new javax.swing.GroupLayout(veiculo_pesquisa);
        veiculo_pesquisa.setLayout(veiculo_pesquisaLayout);
        veiculo_pesquisaLayout.setHorizontalGroup(
            veiculo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        veiculo_pesquisaLayout.setVerticalGroup(
            veiculo_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, veiculo_pesquisaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        veiculo_tab.addTab("Pesquisa", veiculo_pesquisa);

        veiculoCadastroPlaca_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroPlaca_letraActionPerformed(evt);
            }
        });

        veiculoCadastroPlaca_hifen.setText("-");

        veiculoCadastroPlaca_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroPlaca_numeroActionPerformed(evt);
            }
        });

        veiculoCadastroModelo_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroModelo_modeloActionPerformed(evt);
            }
        });

        veiculoCadastroAno_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroAno_anoActionPerformed(evt);
            }
        });

        veiculoCadastroCombustivel_combustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Álcool", "Flex", "Diesel" }));

        veiculoCadastroFabricante_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroFabricante_fabricanteActionPerformed(evt);
            }
        });

        labe_placa.setText("Placa");

        labe_modelo.setText("Modelo");

        labe_fabricante.setText("Fabricante");

        labe__ano.setText("Ano");

        label_tipoDeCombustivel.setText("Tipo de Combustivel");

        labe_fabricante2.setText("Odômetro");

        veiculoCadastroOdometro_odometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroOdometro_odometroActionPerformed(evt);
            }
        });

        botao_cadastrarVeiculo.setText("Cadastrar Veículo");
        botao_cadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cadastrarVeiculoActionPerformed(evt);
            }
        });

        veiculoCadastroTanque_capacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoCadastroTanque_capacidadeActionPerformed(evt);
            }
        });

        labe_fabricante1.setText("Capacidade do tanque");

        javax.swing.GroupLayout veiculo_cadastroLayout = new javax.swing.GroupLayout(veiculo_cadastro);
        veiculo_cadastro.setLayout(veiculo_cadastroLayout);
        veiculo_cadastroLayout.setHorizontalGroup(
            veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                        .addComponent(botao_cadastrarVeiculo)
                        .addGap(261, 261, 261))
                    .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                        .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(veiculoCadastroOdometro_odometro)
                            .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                                .addComponent(veiculoCadastroPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veiculoCadastroPlaca_hifen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veiculoCadastroPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(veiculoCadastroAno_ano))
                        .addGap(18, 18, 18)
                        .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, veiculo_cadastroLayout.createSequentialGroup()
                                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labe_placa, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labe__ano, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(veiculoCadastroModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(veiculoCadastroFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(labe_modelo))
                                    .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(labe_fabricante)))
                                .addGap(33, 33, 33)
                                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(veiculoCadastroTanque_capacidade, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(veiculoCadastroCombustivel_combustivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_tipoDeCombustivel)
                                    .addComponent(labe_fabricante1)))
                            .addComponent(labe_fabricante2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        veiculo_cadastroLayout.setVerticalGroup(
            veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(veiculo_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoCadastroPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoCadastroPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoCadastroPlaca_hifen)
                    .addComponent(veiculoCadastroCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoCadastroModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_placa)
                    .addComponent(labe_modelo)
                    .addComponent(label_tipoDeCombustivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoCadastroAno_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoCadastroFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante)
                    .addComponent(labe__ano)
                    .addComponent(veiculoCadastroTanque_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(veiculo_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(veiculoCadastroOdometro_odometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante2))
                .addGap(17, 17, 17)
                .addComponent(botao_cadastrarVeiculo)
                .addContainerGap(423, Short.MAX_VALUE))
        );

        veiculo_tab.addTab("Cadastro", veiculo_cadastro);

        javax.swing.GroupLayout veiculo_relatorioLayout = new javax.swing.GroupLayout(veiculo_relatorio);
        veiculo_relatorio.setLayout(veiculo_relatorioLayout);
        veiculo_relatorioLayout.setHorizontalGroup(
            veiculo_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 963, Short.MAX_VALUE)
        );
        veiculo_relatorioLayout.setVerticalGroup(
            veiculo_relatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );

        veiculo_tab.addTab("Relatório", veiculo_relatorio);

        jTabbedPane1.addTab("Veiculo", veiculo_tab);

        abastecimentoPesquisaPlaca_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaPlaca_letraActionPerformed(evt);
            }
        });

        abastecimentoloPesquisaPlaca_hifen.setText("-");

        abastecimentoPesquisaPlaca_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaPlaca_numeroActionPerformed(evt);
            }
        });

        abasstecimentoPesquisaPlaca_botao.setText("Placa");

        abastecimentoPesquisaModelo_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaModelo_modeloActionPerformed(evt);
            }
        });

        abastecimentoPesquisaModelo_botao.setText("Modelo");
        abastecimentoPesquisaModelo_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaModelo_botaoActionPerformed(evt);
            }
        });

        abastecimentoPesquisaCombustivel_combustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Álcool", "Flex", "Diesel" }));

        abastecimentoPesquisaCombustivel_botao.setText("Combustivel");
        abastecimentoPesquisaCombustivel_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaCombustivel_botaoActionPerformed(evt);
            }
        });

        abastecimentoPesquisaAno_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaAno_anoActionPerformed(evt);
            }
        });

        abastecimentoPesquisaAno_botao.setText("Ano");
        abastecimentoPesquisaAno_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaAno_botaoActionPerformed(evt);
            }
        });

        abastecimentoPesquisaFabricante_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaFabricante_fabricanteActionPerformed(evt);
            }
        });

        abastecimentoPesquisaFabricante_botao.setText("Fabricante");
        abastecimentoPesquisaFabricante_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoPesquisaFabricante_botaoActionPerformed(evt);
            }
        });

        abastecimentoPesquisaResultado_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String [] {
                "Placa", "tipo", "data","odometro","quantidade", "total", "preco/litro"
            }
        ));
        abastecimentoPesquisaResultado_container.setViewportView(abastecimentoPesquisaResultado_table);

        veiculoPesquisaLista_Todos2.setText("Listar Todos");
        veiculoPesquisaLista_Todos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veiculoPesquisaLista_Todos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abastecimentoPesquisaResultado_container, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(abastecimentoPesquisaAno_ano)
                        .addGap(7, 7, 7)
                        .addComponent(abastecimentoPesquisaAno_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(abastecimentoPesquisaPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abastecimentoloPesquisaPlaca_hifen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abastecimentoPesquisaPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(abasstecimentoPesquisaPlaca_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abastecimentoPesquisaModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoPesquisaFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abastecimentoPesquisaFabricante_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abastecimentoPesquisaModelo_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(abastecimentoPesquisaCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abastecimentoPesquisaCombustivel_botao))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(veiculoPesquisaLista_Todos2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abastecimentoPesquisaPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abasstecimentoPesquisaPlaca_botao)
                    .addComponent(abastecimentoPesquisaPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoloPesquisaPlaca_hifen)
                    .addComponent(abastecimentoPesquisaModelo_botao)
                    .addComponent(abastecimentoPesquisaCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoPesquisaCombustivel_botao)
                    .addComponent(abastecimentoPesquisaModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abastecimentoPesquisaAno_botao)
                    .addComponent(abastecimentoPesquisaAno_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoPesquisaFabricante_botao)
                    .addComponent(abastecimentoPesquisaFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(veiculoPesquisaLista_Todos2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abastecimentoPesquisaResultado_container, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout abatecimento_pesquisaLayout = new javax.swing.GroupLayout(abatecimento_pesquisa);
        abatecimento_pesquisa.setLayout(abatecimento_pesquisaLayout);
        abatecimento_pesquisaLayout.setHorizontalGroup(
            abatecimento_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        abatecimento_pesquisaLayout.setVerticalGroup(
            abatecimento_pesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abatecimento_pesquisaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        abastecimento_tab.addTab("Pesquisa", abatecimento_pesquisa);

        abastecimentoCadastroPlaca_letra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroPlaca_letraActionPerformed(evt);
            }
        });

        abastecimentoloCadastroPlaca_hifen.setText("-");

        abastecimentoCadastroPlaca_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroPlaca_numeroActionPerformed(evt);
            }
        });

        abastecimentoCadastroPlaca_botao.setText("Placa");
        abastecimentoCadastroPlaca_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroPlaca_botaoActionPerformed(evt);
            }
        });

        abastecimentoCadastroModelo_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroModelo_modeloActionPerformed(evt);
            }
        });

        abastecimentoCadastroModelo_botao.setText("Modelo");
        abastecimentoCadastroModelo_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroModelo_botaoActionPerformed(evt);
            }
        });

        abastecimentoCadastroCombustivel_combustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Álcool", "Flex", "Diesel" }));

        abastecimentoCadastroCombustivel_botao.setText("Combustivel");
        abastecimentoCadastroCombustivel_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroCombustivel_botaoActionPerformed(evt);
            }
        });

        abastecimentoCadastroAno_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroAno_anoActionPerformed(evt);
            }
        });

        abastecimentoCadastroAno_botao.setText("Ano");
        abastecimentoCadastroAno_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroAno_botaoActionPerformed(evt);
            }
        });

        abastecimentoCadastroFabricante_fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroFabricante_fabricanteActionPerformed(evt);
            }
        });

        abastecimentoCadastroFabricante_botao.setText("Fabricante");
        abastecimentoCadastroFabricante_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroFabricante_botaoActionPerformed(evt);
            }
        });

        abastecimentoCadastroResultado_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String [] {
                "Placa", "tipo", "data","ano","quantidade", "odometro"
            }
        ));
        abastecimentoCadastroResultado_container.setViewportView(abastecimentoCadastroResultado_table);

        abastecimentoCadastroListaTodos.setText("Listar Todos");
        abastecimentoCadastroListaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroListaTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abastecimentoCadastroResultado_container)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(abastecimentoCadastroAno_ano)
                        .addGap(7, 7, 7)
                        .addComponent(abastecimentoCadastroAno_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(abastecimentoCadastroPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abastecimentoloCadastroPlaca_hifen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abastecimentoCadastroPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(abastecimentoCadastroPlaca_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abastecimentoCadastroModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoCadastroFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(abastecimentoCadastroFabricante_botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(abastecimentoCadastroModelo_botao, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(abastecimentoCadastroCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abastecimentoCadastroCombustivel_botao))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(abastecimentoCadastroListaTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abastecimentoCadastroPlaca_letra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoCadastroPlaca_botao)
                    .addComponent(abastecimentoCadastroPlaca_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoloCadastroPlaca_hifen)
                    .addComponent(abastecimentoCadastroModelo_botao)
                    .addComponent(abastecimentoCadastroCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abastecimentoCadastroCombustivel_botao)
                    .addComponent(abastecimentoCadastroModelo_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abastecimentoCadastroListaTodos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(abastecimentoCadastroAno_botao)
                        .addComponent(abastecimentoCadastroAno_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(abastecimentoCadastroFabricante_botao)
                        .addComponent(abastecimentoCadastroFabricante_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abastecimentoCadastroResultado_container, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
        );

        labe_fabricante3.setText("Odômetro");

        abastecimentoCadastroOdometro_odometro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroOdometro_odometroActionPerformed(evt);
            }
        });

        abastecimentoCadastroTipoDeCombustivel_combustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Álcool", "Diesel" }));

        label_tipoDeCombustivel1.setText("Tipo de Combustivel");

        abastecimentoCadastroBotao_botao.setText("Cadastrar Abastecimento");
        abastecimentoCadastroBotao_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroBotao_botaoActionPerformed(evt);
            }
        });

        labe_fabricante4.setText("Quantidade Abastecida");

        abastecimentoCadastroQuantidadeAbastecida_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroQuantidadeAbastecida_quantidadeActionPerformed(evt);
            }
        });

        abastecimentoCadastroValorAbastecido_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroValorAbastecido_valorActionPerformed(evt);
            }
        });

        labe_fabricante5.setText("Valor Abastecido");

        abastecimentoCadastroInicioDeSerie_checkbox.setSelected(true);
        abastecimentoCadastroInicioDeSerie_checkbox.setText("Início de Série");
        abastecimentoCadastroInicioDeSerie_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abastecimentoCadastroInicioDeSerie_checkboxActionPerformed(evt);
            }
        });

        labe_fabricante6.setText("dia");

        AbastecimentoCadastroData_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbastecimentoCadastroData_diaActionPerformed(evt);
            }
        });

        AbastecimentoCadastroData_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbastecimentoCadastroData_mesActionPerformed(evt);
            }
        });

        labe_fabricante7.setText("mês");

        AbastecimentoCadastroData_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbastecimentoCadastroData_anoActionPerformed(evt);
            }
        });

        labe_fabricante8.setText("ano");

        AbastecimentoCadastroData_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbastecimentoCadastroData_horaActionPerformed(evt);
            }
        });

        labe_fabricante9.setText("hora");

        AbastecimentoCadastroData_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbastecimentoCadastroData_minActionPerformed(evt);
            }
        });

        labe_fabricante10.setText("min");

        javax.swing.GroupLayout abatecimento_cadastroLayout = new javax.swing.GroupLayout(abatecimento_cadastro);
        abatecimento_cadastro.setLayout(abatecimento_cadastroLayout);
        abatecimento_cadastroLayout.setHorizontalGroup(
            abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abatecimento_cadastroLayout.createSequentialGroup()
                .addGap(37, 41, Short.MAX_VALUE)
                .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abatecimento_cadastroLayout.createSequentialGroup()
                        .addComponent(abastecimentoCadastroValorAbastecido_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labe_fabricante5))
                    .addGroup(abatecimento_cadastroLayout.createSequentialGroup()
                        .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(abatecimento_cadastroLayout.createSequentialGroup()
                                .addComponent(abastecimentoCadastroOdometro_odometro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labe_fabricante3))
                            .addGroup(abatecimento_cadastroLayout.createSequentialGroup()
                                .addComponent(abastecimentoCadastroQuantidadeAbastecida_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labe_fabricante4)))
                        .addGap(98, 98, 98)
                        .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abastecimentoCadastroTipoDeCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abastecimentoCadastroInicioDeSerie_checkbox))
                        .addComponent(label_tipoDeCombustivel1))
                    .addGroup(abatecimento_cadastroLayout.createSequentialGroup()
                        .addComponent(AbastecimentoCadastroData_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labe_fabricante6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbastecimentoCadastroData_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labe_fabricante7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbastecimentoCadastroData_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labe_fabricante8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AbastecimentoCadastroData_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labe_fabricante9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(abastecimentoCadastroBotao_botao)
                            .addGroup(abatecimento_cadastroLayout.createSequentialGroup()
                                .addComponent(AbastecimentoCadastroData_min, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labe_fabricante10)))))
                .addGap(354, 354, 354))
        );
        abatecimento_cadastroLayout.setVerticalGroup(
            abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abatecimento_cadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abastecimentoCadastroOdometro_odometro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante3)
                    .addComponent(abastecimentoCadastroTipoDeCombustivel_combustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tipoDeCombustivel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abastecimentoCadastroQuantidadeAbastecida_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante4)
                    .addComponent(abastecimentoCadastroInicioDeSerie_checkbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abastecimentoCadastroValorAbastecido_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abatecimento_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbastecimentoCadastroData_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante6)
                    .addComponent(AbastecimentoCadastroData_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante7)
                    .addComponent(AbastecimentoCadastroData_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante8)
                    .addComponent(AbastecimentoCadastroData_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante9)
                    .addComponent(AbastecimentoCadastroData_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe_fabricante10))
                .addGap(18, 18, 18)
                .addComponent(abastecimentoCadastroBotao_botao)
                .addGap(175, 175, 175))
        );

        abastecimento_tab.addTab("Cadastro", abatecimento_cadastro);

        jTabbedPane1.addTab("Abastecimento", abastecimento_tab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 983, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void veiculoCadastroFabricante_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroFabricante_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroFabricante_fabricanteActionPerformed

    private void veiculoCadastroModelo_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroModelo_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroModelo_modeloActionPerformed

    private void veiculoCadastroAno_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroAno_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroAno_anoActionPerformed

    private void veiculoCadastroPlaca_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroPlaca_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroPlaca_numeroActionPerformed

    private void veiculoCadastroPlaca_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroPlaca_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroPlaca_letraActionPerformed

    private void veiculoPesquisaFabricante_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaFabricante_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaFabricante_fabricanteActionPerformed

    private void veiculoPesquisaModelo_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaModelo_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaModelo_modeloActionPerformed

    private void veiculoPesquisaAno_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaAno_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaAno_anoActionPerformed

    private void veiculoPesquisaPlaca_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaPlaca_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaPlaca_numeroActionPerformed

    private void veiculoPesquisaPlaca_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaPlaca_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaPlaca_letraActionPerformed

    private void botao_cadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cadastrarVeiculoActionPerformed
        String placa = veiculoCadastroPlaca_letra.getText()+veiculoCadastroPlaca_numero.getText();
        String modelo = veiculoCadastroModelo_modelo.getText();
        int ano = Integer.parseInt(veiculoCadastroAno_ano.getText());
        String fabricante = veiculoCadastroFabricante_fabricante.getText();
        int capacidadeDoTanque = Integer.parseInt(veiculoCadastroTanque_capacidade.getText()) ;
        double odometro = Double.parseDouble(veiculoCadastroOdometro_odometro.getText());
        String tipoDecombustivel = veiculoCadastroCombustivel_combustivel.getSelectedItem().toString();
        controller.cadastraVeiculo(placa, modelo, ano, fabricante, capacidadeDoTanque, odometro, tipoDecombustivel);
        facade.add(new Carro(placa, modelo, ano, fabricante, capacidadeDoTanque, odometro, tipoDecombustivel));
    }//GEN-LAST:event_botao_cadastrarVeiculoActionPerformed

    private void veiculoCadastroTanque_capacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroTanque_capacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroTanque_capacidadeActionPerformed

    private void veiculoCadastroOdometro_odometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoCadastroOdometro_odometroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoCadastroOdometro_odometroActionPerformed

    private void veiculoPesquisaLista_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaLista_TodosActionPerformed
       DefaultTableModel model = (DefaultTableModel) VeiculoPesquisaResultado_table.getModel();       
       controller.processaPesquisaGeral(model);        
    }//GEN-LAST:event_veiculoPesquisaLista_TodosActionPerformed

    private void veiculoPesquisaCombustivel_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaCombustivel_botaoActionPerformed
       DefaultTableModel model = (DefaultTableModel) VeiculoPesquisaResultado_table.getModel();  
       String arg = veiculoPesquisaCombustivel_combustivel.getSelectedItem().toString();
       controller.processaPesquisaEspecifica(model,"combustivel", arg);
    }//GEN-LAST:event_veiculoPesquisaCombustivel_botaoActionPerformed

    private void veiculoPesquisaFabricante_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaFabricante_botaoActionPerformed
       DefaultTableModel model = (DefaultTableModel) VeiculoPesquisaResultado_table.getModel();  
       String arg = veiculoPesquisaFabricante_fabricante.getText().toString();
       controller.processaPesquisaEspecifica(model,"fabricante", arg);
    }//GEN-LAST:event_veiculoPesquisaFabricante_botaoActionPerformed

    private void veiculoPesquisaModelo_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaModelo_botaoActionPerformed
       DefaultTableModel model = (DefaultTableModel) VeiculoPesquisaResultado_table.getModel();  
       String arg = veiculoPesquisaModelo_modelo.getText().toString();
       controller.processaPesquisaEspecifica(model,"modelo", arg);
    }//GEN-LAST:event_veiculoPesquisaModelo_botaoActionPerformed

    private void veiculoPesquisaAno_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaAno_botaoActionPerformed
      DefaultTableModel model = (DefaultTableModel) VeiculoPesquisaResultado_table.getModel();  
      String arg = veiculoPesquisaAno_ano.getText().toString();
      controller.processaPesquisaEspecifica(model,"ano", arg);
    }//GEN-LAST:event_veiculoPesquisaAno_botaoActionPerformed

    private void veiculoPesquisaLista_Todos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaLista_Todos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaLista_Todos2ActionPerformed

    private void abastecimentoPesquisaFabricante_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaFabricante_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaFabricante_botaoActionPerformed

    private void abastecimentoPesquisaFabricante_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaFabricante_fabricanteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaFabricante_fabricanteActionPerformed

    private void abastecimentoPesquisaAno_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaAno_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaAno_botaoActionPerformed

    private void abastecimentoPesquisaAno_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaAno_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaAno_anoActionPerformed

    private void abastecimentoPesquisaCombustivel_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaCombustivel_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaCombustivel_botaoActionPerformed

    private void abastecimentoPesquisaModelo_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaModelo_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaModelo_botaoActionPerformed

    private void abastecimentoPesquisaModelo_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaModelo_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaModelo_modeloActionPerformed

    private void abastecimentoPesquisaPlaca_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaPlaca_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaPlaca_numeroActionPerformed

    private void abastecimentoPesquisaPlaca_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoPesquisaPlaca_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoPesquisaPlaca_letraActionPerformed

    private void abastecimentoCadastroQuantidadeAbastecida_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroQuantidadeAbastecida_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroQuantidadeAbastecida_quantidadeActionPerformed

    private void abastecimentoCadastroBotao_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroBotao_botaoActionPerformed
        // criando variaveis para alimentar o objeto Abastecimento a ser adicionado no cadastroDeAbastecimentos do objeto Carro
        double odometro = Double.parseDouble(abastecimentoCadastroOdometro_odometro.getText());
        String tipoDeCombustivel = abastecimentoCadastroTipoDeCombustivel_combustivel.getSelectedItem().toString();
        double quantidadeAbastecida = Double.parseDouble(abastecimentoCadastroQuantidadeAbastecida_quantidade.getText());
        double valorAbastecido = Double.parseDouble(abastecimentoCadastroValorAbastecido_valor.getText());
        boolean inicioDeSerie = abastecimentoCadastroInicioDeSerie_checkbox.isSelected();
        int dia = Integer.parseInt(AbastecimentoCadastroData_dia.getText());
        int mes = Integer.parseInt(AbastecimentoCadastroData_mes.getText());
        int ano = Integer.parseInt(AbastecimentoCadastroData_ano.getText());
        int hora = Integer.parseInt(AbastecimentoCadastroData_hora.getText());
        int minuto = Integer.parseInt(AbastecimentoCadastroData_min.getText());        
        Date diaDoAbastecimento = new Date(ano, mes, dia, hora, minuto);
        double precoLitro = valorAbastecido/quantidadeAbastecida;
        
        //alimentando o abastecimento
        negocio.Abastecimento abastecimento = new negocio.Abastecimento(tipoDeCombustivel, diaDoAbastecimento, odometro, quantidadeAbastecida, valorAbastecido, precoLitro, inicioDeSerie);
        int linha = abastecimentoCadastroResultado_table.getSelectedRow();
        String placa = 	abastecimentoCadastroResultado_table.getValueAt(linha,0).toString();
        DefaultTableModel model = (DefaultTableModel) abastecimentoCadastroResultado_table.getModel();       
        Carro carro = facade.pesquisaPlaca(placa);
        carro.getHistoricoDeAbastecimentos().add(abastecimento);
                
    }//GEN-LAST:event_abastecimentoCadastroBotao_botaoActionPerformed

    private void abastecimentoCadastroOdometro_odometroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroOdometro_odometroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroOdometro_odometroActionPerformed

    private void abastecimentoCadastroListaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroListaTodosActionPerformed
       DefaultTableModel model = (DefaultTableModel) abastecimentoCadastroResultado_table.getModel();       
       controller.processaPesquisaGeral(model);    
    }//GEN-LAST:event_abastecimentoCadastroListaTodosActionPerformed

    private void abastecimentoCadastroFabricante_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroFabricante_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroFabricante_botaoActionPerformed

    private void abastecimentoCadastroFabricante_fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroFabricante_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroFabricante_fabricanteActionPerformed

    private void abastecimentoCadastroAno_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroAno_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroAno_botaoActionPerformed

    private void abastecimentoCadastroAno_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroAno_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroAno_anoActionPerformed

    private void abastecimentoCadastroCombustivel_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroCombustivel_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroCombustivel_botaoActionPerformed

    private void abastecimentoCadastroModelo_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroModelo_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroModelo_botaoActionPerformed

    private void abastecimentoCadastroModelo_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroModelo_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroModelo_modeloActionPerformed

    private void abastecimentoCadastroPlaca_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroPlaca_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroPlaca_numeroActionPerformed

    private void abastecimentoCadastroPlaca_letraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroPlaca_letraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroPlaca_letraActionPerformed

    private void abastecimentoCadastroValorAbastecido_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroValorAbastecido_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroValorAbastecido_valorActionPerformed

    private void AbastecimentoCadastroData_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbastecimentoCadastroData_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbastecimentoCadastroData_diaActionPerformed

    private void AbastecimentoCadastroData_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbastecimentoCadastroData_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbastecimentoCadastroData_mesActionPerformed

    private void AbastecimentoCadastroData_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbastecimentoCadastroData_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbastecimentoCadastroData_anoActionPerformed

    private void AbastecimentoCadastroData_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbastecimentoCadastroData_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbastecimentoCadastroData_horaActionPerformed

    private void AbastecimentoCadastroData_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbastecimentoCadastroData_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbastecimentoCadastroData_minActionPerformed

    private void abastecimentoCadastroInicioDeSerie_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroInicioDeSerie_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroInicioDeSerie_checkboxActionPerformed

    private void abastecimentoCadastroPlaca_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abastecimentoCadastroPlaca_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abastecimentoCadastroPlaca_botaoActionPerformed

    private void veiculoPesquisaPlaca_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veiculoPesquisaPlaca_botaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veiculoPesquisaPlaca_botaoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AbastecimentoCadastroData_ano;
    private javax.swing.JTextField AbastecimentoCadastroData_dia;
    private javax.swing.JTextField AbastecimentoCadastroData_hora;
    private javax.swing.JTextField AbastecimentoCadastroData_mes;
    private javax.swing.JTextField AbastecimentoCadastroData_min;
    private javax.swing.JScrollPane VeiculoPesquisaResultado_container;
    private javax.swing.JTable VeiculoPesquisaResultado_table;
    private javax.swing.JButton abasstecimentoPesquisaPlaca_botao;
    private javax.swing.JTextField abastecimentoCadastroAno_ano;
    private javax.swing.JButton abastecimentoCadastroAno_botao;
    private javax.swing.JButton abastecimentoCadastroBotao_botao;
    private javax.swing.JButton abastecimentoCadastroCombustivel_botao;
    private javax.swing.JComboBox<String> abastecimentoCadastroCombustivel_combustivel;
    private javax.swing.JButton abastecimentoCadastroFabricante_botao;
    private javax.swing.JTextField abastecimentoCadastroFabricante_fabricante;
    private javax.swing.JCheckBox abastecimentoCadastroInicioDeSerie_checkbox;
    private javax.swing.JButton abastecimentoCadastroListaTodos;
    private javax.swing.JButton abastecimentoCadastroModelo_botao;
    private javax.swing.JTextField abastecimentoCadastroModelo_modelo;
    private javax.swing.JTextField abastecimentoCadastroOdometro_odometro;
    private javax.swing.JButton abastecimentoCadastroPlaca_botao;
    private javax.swing.JTextField abastecimentoCadastroPlaca_letra;
    private javax.swing.JTextField abastecimentoCadastroPlaca_numero;
    private javax.swing.JTextField abastecimentoCadastroQuantidadeAbastecida_quantidade;
    private javax.swing.JScrollPane abastecimentoCadastroResultado_container;
    private javax.swing.JTable abastecimentoCadastroResultado_table;
    private javax.swing.JComboBox<String> abastecimentoCadastroTipoDeCombustivel_combustivel;
    private javax.swing.JTextField abastecimentoCadastroValorAbastecido_valor;
    private javax.swing.JTextField abastecimentoPesquisaAno_ano;
    private javax.swing.JButton abastecimentoPesquisaAno_botao;
    private javax.swing.JButton abastecimentoPesquisaCombustivel_botao;
    private javax.swing.JComboBox<String> abastecimentoPesquisaCombustivel_combustivel;
    private javax.swing.JButton abastecimentoPesquisaFabricante_botao;
    private javax.swing.JTextField abastecimentoPesquisaFabricante_fabricante;
    private javax.swing.JButton abastecimentoPesquisaModelo_botao;
    private javax.swing.JTextField abastecimentoPesquisaModelo_modelo;
    private javax.swing.JTextField abastecimentoPesquisaPlaca_letra;
    private javax.swing.JTextField abastecimentoPesquisaPlaca_numero;
    private javax.swing.JScrollPane abastecimentoPesquisaResultado_container;
    private javax.swing.JTable abastecimentoPesquisaResultado_table;
    private javax.swing.JTabbedPane abastecimento_tab;
    private javax.swing.JLabel abastecimentoloCadastroPlaca_hifen;
    private javax.swing.JLabel abastecimentoloPesquisaPlaca_hifen;
    private javax.swing.JPanel abatecimento_cadastro;
    private javax.swing.JPanel abatecimento_pesquisa;
    private javax.swing.JButton botao_cadastrarVeiculo;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labe__ano;
    private javax.swing.JLabel labe_fabricante;
    private javax.swing.JLabel labe_fabricante1;
    private javax.swing.JLabel labe_fabricante10;
    private javax.swing.JLabel labe_fabricante2;
    private javax.swing.JLabel labe_fabricante3;
    private javax.swing.JLabel labe_fabricante4;
    private javax.swing.JLabel labe_fabricante5;
    private javax.swing.JLabel labe_fabricante6;
    private javax.swing.JLabel labe_fabricante7;
    private javax.swing.JLabel labe_fabricante8;
    private javax.swing.JLabel labe_fabricante9;
    private javax.swing.JLabel labe_modelo;
    private javax.swing.JLabel labe_placa;
    private javax.swing.JLabel label_tipoDeCombustivel;
    private javax.swing.JLabel label_tipoDeCombustivel1;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel resumo_view;
    private javax.swing.JTextField veiculoCadastroAno_ano;
    private javax.swing.JComboBox<String> veiculoCadastroCombustivel_combustivel;
    private javax.swing.JTextField veiculoCadastroFabricante_fabricante;
    private javax.swing.JTextField veiculoCadastroModelo_modelo;
    private javax.swing.JTextField veiculoCadastroOdometro_odometro;
    private javax.swing.JLabel veiculoCadastroPlaca_hifen;
    private javax.swing.JTextField veiculoCadastroPlaca_letra;
    private javax.swing.JTextField veiculoCadastroPlaca_numero;
    private javax.swing.JTextField veiculoCadastroTanque_capacidade;
    private javax.swing.JTextField veiculoPesquisaAno_ano;
    private javax.swing.JButton veiculoPesquisaAno_botao;
    private javax.swing.JButton veiculoPesquisaCombustivel_botao;
    private javax.swing.JComboBox<String> veiculoPesquisaCombustivel_combustivel;
    private javax.swing.JButton veiculoPesquisaFabricante_botao;
    private javax.swing.JTextField veiculoPesquisaFabricante_fabricante;
    private javax.swing.JButton veiculoPesquisaLista_Todos;
    private javax.swing.JButton veiculoPesquisaLista_Todos2;
    private javax.swing.JButton veiculoPesquisaModelo_botao;
    private javax.swing.JTextField veiculoPesquisaModelo_modelo;
    private javax.swing.JButton veiculoPesquisaPlaca_botao;
    private javax.swing.JLabel veiculoPesquisaPlaca_hifen;
    private javax.swing.JTextField veiculoPesquisaPlaca_letra;
    private javax.swing.JTextField veiculoPesquisaPlaca_numero;
    private javax.swing.JPanel veiculo_cadastro;
    private javax.swing.JPanel veiculo_pesquisa;
    private javax.swing.JPanel veiculo_relatorio;
    private javax.swing.JTabbedPane veiculo_tab;
    // End of variables declaration//GEN-END:variables
}
